import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { fetchQuiz, QuestionRoundType, QuestionType, QuizType } from './quizAPI'
import { RootState } from '../../app/store'
import { checkActivityType } from '../../lib/helpers'

export interface QuizState {
  value: QuizType
  status: 'idle' | 'loading' | 'failed'
}

export type QuestionPayload = {
  activityId: number
  questionId: number
}

export type RoundPayload = {
  activityId: number
  roundId: number
}

export type AnswerPayload = {
  activityId: number
  user_answer: boolean
}

export type ActivityTypePayload = {
  activityId: number
  type: 'round' | 'question' | undefined
}

// Define the initial value for the slice state
const initialState: QuizState = {
  value: { name: '', heading: '', activities: [] },
  status: 'idle',
}

// Slices contain Redux reducer logic for updating state, and
// generate actions that can be dispatched to trigger those updates.
export const quizSlice = createSlice({
  name: 'quiz',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // increment: (state) => {
    //   // Redux Toolkit allows us to write "mutating" logic in reducers. It
    //   // doesn't actually mutate the state because it uses the Immer library,
    //   // which detects changes to a "draft state" and produces a brand new
    //   // immutable state based off those changes
    //   state.value += 1
    // },
    // decrement: (state) => {
    //   state.value -= 1
    // },
    // // Use the PayloadAction type to declare the contents of `action.payload`
    setQuestionId: (state, action: PayloadAction<QuestionPayload>) => {
      // state.value += action.payload
      const { activityId, questionId } = action.payload
      state.value.activities[activityId].current_question = questionId
    },
    setRoundId: (state, action: PayloadAction<RoundPayload>) => {
      // state.value += action.payload
      const { activityId, roundId } = action.payload
      state.value.activities[activityId].current_round = roundId
    },
    setActivityType: (state, action: PayloadAction<ActivityTypePayload>) => {
      // state.value += action.payload
      const { activityId, type } = action.payload
      state.value.activities[activityId].type = type
    },
    setAnswer: (state, action: PayloadAction<AnswerPayload>) => {
      const { activityId, user_answer } = action.payload
      const question = getQuestionFromActivity(state, activityId)
      question.user_answers = user_answer
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      // Handle the action types defined by the `incrementAsync` thunk defined below.
      // This lets the slice reducer update the state with request status and results.
      .addCase(getQuiz.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(getQuiz.fulfilled, (state, action) => {
        state.status = 'idle'
        state.value = action.payload
      })
      .addCase(getQuiz.rejected, (state, action) => {
        console.error(action.error)
        state.status = 'failed'
      })
  },
})

// Export the generated action creators for use in components
export const { setQuestionId, setRoundId, setAnswer, setActivityType } = quizSlice.actions

// Export the slice reducer for use in the store configuration
export default quizSlice.reducer

// Selector functions allows us to select a value from the Redux root state.
// Selectors can also be defined inline in the `useSelector` call
// in a component, or inside the `createSlice.selectors` field.
export const selectQuiz = (state: RootState) => state.quiz.value
export const selectStatus = (state: RootState) => state.quiz.status
export const selectIsFetched = (state: RootState) => state.quiz.value.name
export const selectActivityType = (
  state: RootState,
  activityId: number
): 'round' | 'question' | undefined => state.quiz.value.activities?.[activityId]?.type
export const selectQuestionByActivityId = (state: RootState, activityId: number): QuestionType =>
  getQuestionFromActivity(state.quiz, activityId)

export const selectQuestionsLength = (state: RootState, activityId: number): number =>
  getQuestionsFromActivity(state.quiz, activityId).length

export const selectCurrentQuestion = (state: RootState, activityId: number): number | undefined =>
  state.quiz.value.activities?.[activityId]?.current_question

export const selectCurrentRound = (state: RootState, activityId: number): number | undefined =>
  state.quiz.value.activities?.[activityId]?.current_round

export const selectRoundLength = (state: RootState, activityId: number): number =>
  state.quiz.value.activities?.[activityId]?.questions.length

const getQuestionFromActivity = (state: QuizState, activityId: number): QuestionType => {
  const questions = getQuestionsFromActivity(state, activityId)
  const currentQuestion = state.value.activities?.[activityId]?.current_question
  if (currentQuestion === undefined) return ''
  return questions[currentQuestion]
  // const activity = state.value.activities?.[activityId]
  // const activityType = checkActivityType(activity.questions)
  // const currentQuestion = activity?.current_question
  // if (currentQuestion === undefined) return ''
  // switch (activityType) {
  //   case 'round':
  //     const currentRound = activity?.current_round
  //     if (currentRound === undefined) return ''
  //     const round = activity.questions[currentRound] as QuestionRoundType
  //     return round.questions[currentQuestion]
  //   case 'question':
  //     return activity.questions?.[currentQuestion] as QuestionType
  //   default:
  //     return ''
  // }
}

const getQuestionsFromActivity = (state: QuizState, activityId: number): QuestionType[] => {
  const activity = state.value.activities?.[activityId]
  const activityType = activity.type

  switch (activityType) {
    case 'round':
      const currentRound = activity?.current_round
      if (currentRound === undefined) return ''
      const round = activity.questions[currentRound] as QuestionRoundType
      return round.questions
    case 'question':
      return activity.questions as QuestionType[]
    default:
      return ''
  }
}

export const getQuiz = createAsyncThunk('quiz/fetchQuiz', async () => {
  const response = await fetchQuiz()
  return response
})
