import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { fetchQuiz, QuizType } from './quizAPI'
import { RootState } from '../../app/store'

export interface QuizState {
  value: QuizType
  status: 'idle' | 'loading' | 'failed'
}

// Define the initial value for the slice state
const initialState: QuizState = {
  value: { name: '', heading: '', activities: [] },
  status: 'idle',
}

// Slices contain Redux reducer logic for updating state, and
// generate actions that can be dispatched to trigger those updates.
export const quizSlice = createSlice({
  name: 'quiz',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // increment: (state) => {
    //   // Redux Toolkit allows us to write "mutating" logic in reducers. It
    //   // doesn't actually mutate the state because it uses the Immer library,
    //   // which detects changes to a "draft state" and produces a brand new
    //   // immutable state based off those changes
    //   state.value += 1
    // },
    // decrement: (state) => {
    //   state.value -= 1
    // },
    // // Use the PayloadAction type to declare the contents of `action.payload`
    // incrementByAmount: (state, action: PayloadAction<number>) => {
    //   state.value += action.payload
    // },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      // Handle the action types defined by the `incrementAsync` thunk defined below.
      // This lets the slice reducer update the state with request status and results.
      .addCase(getQuiz.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(getQuiz.fulfilled, (state, action) => {
        state.status = 'idle'
        state.value = action.payload
      })
      .addCase(getQuiz.rejected, (state, action) => {
        console.error(action.error)
        state.status = 'failed'
      })
  },
})

// Export the generated action creators for use in components
// export const { increment, decrement, incrementByAmount } = quizSlice.actions

// Export the slice reducer for use in the store configuration
export default quizSlice.reducer

// Selector functions allows us to select a value from the Redux root state.
// Selectors can also be defined inline in the `useSelector` call
// in a component, or inside the `createSlice.selectors` field.
export const selectQuiz = (state: RootState) => state.quiz.value
export const selectStatus = (state: RootState) => state.quiz.status
export const selectIsFetched = (state: RootState) => state.quiz.value.name
export const selectQuestionByIndex = (state: RootState, activityId: number) =>
  state.quiz.value.activities?.[activityId]

export const getQuiz = createAsyncThunk('quiz/fetchQuiz', async () => {
  const response = await fetchQuiz()
  return response
})
